alg: BehaviorCloning
alg_kwargs:
  # Configure offline steps. These aren't needed, but good to set.
  offline_steps: -1
  random_steps: 0

optim: Adam
optim_kwargs:
  lr: 0.0003

network: ActorPolicy
network_kwargs:
  actor_class: ContinuousMLPActor
  hidden_layers: [256, 256]
  ortho_init: True

eval_env: hopper-medium-expert-v2

dataset: D4RLDataset
dataset_kwargs:
  d4rl_path: ../datasets/d4rl/
  name: hopper-medium-expert-v2
  sample_fn: sample
  sample_kwargs:
    batch_size: 256
  exclude_keys: [reward, discount] # Cannot exclude done.
  normalize_reward: True
  reward_scale: 1000.0 # scale to 1000 like in IQL
  use_rtg: False
  use_timesteps: False
  action_eps: 0.00001 # necesary to prevent NaN in the dataset.

schedule: null
processor: null

trainer_kwargs: # Arguments given to Algorithm.train
  total_steps: 1000000 # The total number of steps to train
  log_freq: 250 # How often to log values
  profile_freq: 100
  eval_freq: 10000 # How often to run evals
  eval_fn: eval_policy
  eval_kwargs:
    num_ep: 10 # Number of enviornment episodes to run for evaluation, or -1 if none should be run.
  loss_metric: reward # The validation metric that determines when to save the "best_checkpoint"
  train_dataloader_kwargs:
    num_workers: 0 # Number of dataloader workers.
    batch_size: null
